# Generated by Django 3.2.7 on 2021-11-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=200)),
                ('Patient', models.CharField(max_length=200)),
                ('Sequence', models.CharField(choices=[('DNA', 'DNA'), ('FFPE', 'FFPE'), ('RNA', 'RNA'), ('null', 'null')], max_length=200, null=True)),
                ('Fastqcfol', models.CharField(max_length=100, null=True)),
                ('Samplename', models.CharField(max_length=100, null=True)),
                ('Sample', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sequence', models.CharField(choices=[('DNA', 'DNA'), ('FFPE', 'FFPE'), ('RNA', 'RNA'), ('null', 'null')], max_length=100)),
                ('FastQc', models.CharField(max_length=200)),
                ('Sample_name', models.CharField(max_length=200)),
                ('Path_name', models.CharField(max_length=200)),
                ('Tru_Sequence', models.CharField(max_length=200)),
                ('Flowcell', models.CharField(max_length=200)),
                ('Lane', models.CharField(max_length=200)),
                ('Row', models.CharField(max_length=200)),
                ('BS', models.CharField(max_length=200)),
                ('PBSQ', models.CharField(max_length=200)),
                ('PTSQ', models.CharField(max_length=200)),
                ('PSQS', models.CharField(max_length=200)),
                ('PBSC', models.CharField(max_length=200)),
                ('PSGC', models.CharField(max_length=200)),
                ('PBNC', models.CharField(max_length=200)),
                ('SLD', models.CharField(max_length=200)),
                ('SDL', models.CharField(max_length=200)),
                ('OS', models.CharField(max_length=200)),
                ('AC', models.CharField(max_length=200)),
                ('Total_Sequence', models.CharField(max_length=200)),
                ('Sequence_length', models.CharField(max_length=200)),
                ('GC', models.CharField(max_length=200)),
            ],
        ),
    ]
