# Generated by Django 3.2.7 on 2021-10-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='Sequence',
            field=models.CharField(choices=[('DNA', 'DNA'), ('FFPE', 'FFPE'), ('RNA', 'RNA'), ('Null', 'Null')], max_length=100),
        ),
        migrations.AlterField(
            model_name='data2',
            name='Sequence',
            field=models.CharField(choices=[('DNA', 'DNA'), ('FFPE', 'FFPE'), ('RNA', 'RNA'), ('Null', 'Null')], max_length=100),
        ),
    ]
