# Generated by Django 3.2.7 on 2021-11-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211027_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTable',
        ),
    ]
